### PR TITLE
Merge feature/87-mailhog

### LINKED ISSUE #87: Install mailhog instead of mailcatcher
Install mailhog instead of mailcatcher.

Check if Mailhog works inside an iframe (see #13)

### PR DESCRIPTION
**Pull request by stevenrombauts**
Closes #87

### CODE REVIEW

**Comment by stevenrombauts** [comment]
@yiendos This is looking good to go, I've only added the `mhsendmail` binary so that the `sendmail_path` directive in php.ini points to a working binary (it pointed to `catchmail` which came with the mailcatcher files).  Our Joomla installs don't depend on it because we configure every new install to use SMTP but this just makes sure everything works. You can test it easily with this little script:

```php
<?php
if (mail('to@foo.com', 'Test message!', 'Lorum lipsum', 'From: from@foo.com')) {
    echo "Message accepted\n";
} else {
    echo "Error: Message not accepted\n";
}
```

**Comment by yiendos** [comment]
@stevenrombauts Ooo nice catch with the `mhsendmail` binary. I notice here we drop support for catchmail as you've explained:
https://github.com/joomlatools/joomlatools-vagrant/pull/141/commits/479705b532a4c336a1450440e9a6e12328e18fc7#diff-d694e7ebd8c616557f1a3df528db7d16L25

But don't we also set the joomla configuration via `joomla site:create testing` command. Looking at typical configuration file created via this route we have: 

```
public $sendmail = '/usr/bin/env catchmail';
```

Which differs from the standard vanila J configuration:
https://github.com/joomla/joomla-cms/blob/staging/installation/configuration.php-dist#L88

But the only trace I can find of this configuration in the joomlatools-console repo relates to the configuration of codeKit:
https://github.com/joomlatools/joomlatools-console/blob/master/src/Joomlatools/Console/Command/Site/Configure.php#L250

I'd say we'd also need to update the console as well?

**Comment by yiendos** [comment]
@stevenrombauts I should have read your earlier comments better: 
`Our Joomla installs don't depend on it because we configure every new install to use SMTP` 

Indeed a new install from `site:create` is capable of sending mail because of the `smtp` setting

**Comment by yiendos** [comment]
@stevenrombauts tested and working like a dream on a clean install of the box.

**Comment by stevenrombauts** [comment]
@yiendos Sorry, I removed the `catchmail` reference from console [yesterday](https://github.com/joomlatools/joomlatools-console/commit/4c0defc0732416c184d036a9d5babe3d553cc2bf#diff-3e9f0dbcf8533fd826663f70e6c3a797), but I didn't see the second one for kodekit config. Removed that now as well.

Thanks for testing, this can be merged into master then, ready for the next release.

**Pull request merged**
